version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: laser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: games

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
