spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: laser
    password: secret
  jpa:
    generate-ddl: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: "classpath:sql"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
