spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: laser
    password: secret
  sql:
    init:
      mode: embedded
      continue-on-error: true
      data-locations: "classpath:sql"

